spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mymobileservice
    username: root
    password: root
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true